# Setup

In [96]:
# user setup
import os

# custom Kaggle login (environment variables are recommended)
os.environ["KAGGLE_USERNAME"] = "" or os.getenv("KAGGLE_USERNAME")
os.environ["KAGGLE_KEY"] = "" or os.getenv("KAGGLE_KEY")

# use spark (distributed MapReduce) or pandas (local computation)
LOCAL_COMPUTATION = False

# spark configuration
os.environ["JAVA_HOME"] = "" or "/usr/lib/jvm/java-17-openjdk-amd64"
os.environ["SPARK_HOME"] = "" or "/content/spark"

# subsampling: percentage of commenting users to keep
USERS_PERCENTAGE = 0.1
assert 0 < USERS_PERCENTAGE <= 1, "invalid USER_PERCENTAGE, should be in (0, 1]"

In [97]:
# setup dataset
%pip install kaggle
!test -d dataset && echo "Skipping dataset download" || (kaggle datasets download -d "benjaminawd/new-york-times-articles-comments-2020" && unzip -d dataset new-york-times-articles-comments-2020.zip && rm -f new-york-times-articles-comments-2020.zip 2> /dev/null)

Requirement already satisfied: kaggle in /opt/conda/lib/python3.11/site-packages (2.0.0)
Requirement already satisfied: bleach in /opt/conda/lib/python3.11/site-packages (from kaggle) (6.1.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.15 in /opt/conda/lib/python3.11/site-packages (from kaggle) (0.1.16)
Requirement already satisfied: packaging in /opt/conda/lib/python3.11/site-packages (from kaggle) (23.2)
Requirement already satisfied: protobuf in /opt/conda/lib/python3.11/site-packages (from kaggle) (4.24.3)
Requirement already satisfied: python-dateutil in /opt/conda/lib/python3.11/site-packages (from kaggle) (2.8.2)
Requirement already satisfied: python-slugify in /opt/conda/lib/python3.11/site-packages (from kaggle) (8.0.4)
Requirement already satisfied: requests in /opt/conda/lib/python3.11/site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in /opt/conda/lib/python3.11/site-packages (from kaggle) (4.66.1)
Requirement already satisfied: urllib3>=1.15.1 in /opt/conda/lib/python3.11/site-packages (from kaggle) (2.0.7)
Requirement already satisfied: six>=1.9.0 in /opt/conda/lib/python3.11/site-packages (from bleach->kaggle) (1.16.0)
Requirement already satisfied: webencodings in /opt/conda/lib/python3.11/site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in /opt/conda/lib/python3.11/site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.11/site-packages (from requests->kaggle) (3.3.0)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.11/site-packages (from requests->kaggle) (3.4)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.11/site-packages (from requests->kaggle) (2023.7.22)
Note: you may need to restart the kernel to use updated packages.
Skipping dataset download

In [98]:
# setup spark
!test -d spark && echo "Skipping spark download" || (wget -q https://dlcdn.apache.org/spark/spark-4.1.1/spark-4.1.1-bin-hadoop3.tgz -O spark.tgz && mkdir spark && tar xvf spark.tgz -C spark --strip-components=1 > /dev/null && rm spark.tgz)
%pip install pyspark
%pip install py4j

Skipping spark download
Requirement already satisfied: pyspark in /usr/local/spark/python (3.5.0)
Requirement already satisfied: py4j==0.10.9.7 in /opt/conda/lib/python3.11/site-packages (from pyspark) (0.10.9.7)
Note: you may need to restart the kernel to use updated packages.
Requirement already satisfied: py4j in /opt/conda/lib/python3.11/site-packages (0.10.9.7)
Note: you may need to restart the kernel to use updated packages.

In [99]:
# setup pandas (tests before scaling to spark)
%pip install pandas
import pandas as pd
articles = pd.read_csv("dataset/nyt-articles-2020.csv")
comments = pd.read_csv("dataset/nyt-comments-part0.csv") # TODO: this is already a sample
print(f"Dataset size: {len(articles)=}, {len(comments)=}")
(articles.columns, comments.columns)

Requirement already satisfied: pandas in /opt/conda/lib/python3.11/site-packages (2.0.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.11/site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in /opt/conda/lib/python3.11/site-packages (from pandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /opt/conda/lib/python3.11/site-packages (from pandas) (1.24.4)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.
Dataset size: len(articles)=16787, len(comments)=500000

(Index(['newsdesk', 'section', 'subsection', 'material', 'headline', 'abstract',
        'keywords', 'word_count', 'pub_date', 'n_comments', 'uniqueID'],
       dtype='object'),
 Index(['commentID', 'status', 'commentSequence', 'userID', 'userDisplayName',
        'userLocation', 'userTitle', 'commentBody', 'createDate', 'updateDate',
        'approveDate', 'recommendations', 'replyCount', 'editorsSelection',
        'parentID', 'parentUserDisplayName', 'depth', 'commentType', 'trusted',
        'recommendedFlag', 'permID', 'isAnonymous', 'articleID'],
       dtype='object'))

In [100]:
# subsampling
# WARNING: executing this cell multiple times without executing previous cell will continue to shrink the dataset
if USERS_PERCENTAGE < 1:
    total_users = len(comments['userID'].unique())
    subsampled_users = int(total_users * USERS_PERCENTAGE)
    top_users = comments['userID'].value_counts().nlargest(subsampled_users).index # keep top users
    print(top_users) # TODO

    print(f"Subsampling from {total_users} to {subsampled_users} users:")

    print(f"- comments: {len(comments)} -> ", end="")
    comments = comments[comments['userID'].isin(top_users)].copy() # keep only comments from these users
    print(f"{len(comments)}")

    active_article_ids = comments['articleID'].unique() # keep only commented articles
    print(f"- articles: {len(articles)} -> ", end="")
    articles = articles[articles['uniqueID'].isin(active_article_ids)].copy() # keep only commented articles
    print(f"{len(articles)}")

Index([ 67892453,  68938663,  73444633,  33668404,  69498476,  78358680,
        63483890,  72967915,  87081404,  93082167,
       ...
        49632588,     61360,  80245071,  22822988,  28571829,  21227474,
        65684325, 103084739,  78118899,  42471841],
      dtype='int64', name='userID', length=9143)
Subsampling from 91437 to 9143 users:
- comments: 500000 -> 313145
- articles: 16787 -> 1593

# Utility Matrix

In [101]:
utility_matrix = pd.crosstab(index=comments['userID'], columns=comments['articleID'])
utility_matrix = (utility_matrix > 0).astype(int) # ignore multiple comments on the same article
utility_matrix

articleID,nyt://article/00036db7-8494-5141-b0ac-414118caabee,nyt://article/00168469-d42e-5a6f-9c81-90e3306c6c85,nyt://article/004716c5-8943-5bf4-8293-864ab083d676,nyt://article/00573cb4-92bb-53b7-ad9a-6d4d1e734704,nyt://article/00bea7d5-c04a-509d-a82f-7537a16dfeb1,nyt://article/012aeb93-8149-522b-a18b-d6cfc620fb22,nyt://article/016cf3b3-56e9-53e4-882c-549209211afb,nyt://article/0178a7cd-b6b8-58b2-afe4-3d1f68aef248,nyt://article/01a433cd-37ce-5e77-a39b-fe4af162a34f,nyt://article/01b7c5aa-9cf5-56a0-8162-3b8d606ce533,...,nyt://interactive/c46aa52e-ec78-5e20-8145-acaa9d1d5705,nyt://interactive/c696fd2f-2287-562e-91ec-3f07747a9923,nyt://interactive/c6ec5381-c3f8-5a71-b23a-a0d9b18c7237,nyt://interactive/c891ed57-1184-52d9-bd9c-cf9f7bf23f13,nyt://interactive/d0598a7b-06ba-56db-9df4-7a2afa1c95e3,nyt://interactive/dcc11686-2ae2-562c-9e2b-738e9140b9d4,nyt://interactive/df6cd908-52b0-5851-ac81-e7b8039d50d1,nyt://interactive/e31c6ca3-4bea-5a56-b358-7986e7590f1d,nyt://interactive/e5bd1257-4e08-5656-bc03-091a2597e336,nyt://interactive/f91ad36a-9e5c-5e95-a210-37f1b797fdf3
userID,,,,,,,,,,,,,,,,,,,,,
2593,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8010,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8638,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
13323,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
17282,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109551783,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109587542,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109738098,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109837657,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109978040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Content-Based Recommendations

### Articles Profile

In [102]:
# items profile
feature_columns = ["newsdesk", "section", "subsection"]
item_features_matrix = pd.get_dummies(articles[feature_columns], dtype=int)
item_features_matrix.index = articles['uniqueID'].values
# articles["profile"] = item_features_matrix.values.tolist()
item_features_matrix

,newsdesk_Arts,newsdesk_Arts&Leisure,newsdesk_BookReview,newsdesk_Books,newsdesk_Business,newsdesk_Climate,newsdesk_Culture,newsdesk_Dining,newsdesk_Editorial,newsdesk_Express,...,subsection_Pro Football,subsection_Self-Care,subsection_Skiing,subsection_Soccer,subsection_Sunday Review,subsection_Television,subsection_Tennis,subsection_The Daily,subsection_Weddings,"subsection_Wine, Beer & Cocktails"
nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/9edddb54-0aa3-5835-a833-d311a76f1e7c,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/04bc90f0-b20b-511c-b5bb-3ce13194163f,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/bd8647b3-8ec6-50aa-95cf-2b81ed12d2dd,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/ac742403-9ccd-522f-9a1e-a90feb6c0acd,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
nyt://article/b9c293a0-dfb4-5630-9948-8a39be8afce8,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
nyt://article/203dd447-5d08-5745-95b8-b97de174d4b9,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
nyt://article/1e2029bd-8b3d-5e1e-9e78-28e5ff746998,0,0,0,0,0,0,0,0,0,0,...,1,0,0,0,0,0,0,0,0,0
nyt://article/697c75a8-2600-5e81-98ac-38193d89ae12,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
nyt://article/49cedd40-d966-5fa1-a04a-1db9abc2756a,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Users Profile

In [103]:
# user profile: count how many times each user commented on articles with each label
user_profiles = []

for user_id in utility_matrix.index:
    commented_articles = utility_matrix.loc[user_id][utility_matrix.loc[user_id] == 1].index # articles commented by this user
    user_profile = item_features_matrix.loc[item_features_matrix.index.isin(commented_articles)].sum(axis=0) # sum features vectors for these articles
    user_profiles.append(user_profile)

user_features_matrix = pd.DataFrame(user_profiles, index=utility_matrix.index)
user_features_matrix

,newsdesk_Arts,newsdesk_Arts&Leisure,newsdesk_BookReview,newsdesk_Books,newsdesk_Business,newsdesk_Climate,newsdesk_Culture,newsdesk_Dining,newsdesk_Editorial,newsdesk_Express,...,subsection_Pro Football,subsection_Self-Care,subsection_Skiing,subsection_Soccer,subsection_Sunday Review,subsection_Television,subsection_Tennis,subsection_The Daily,subsection_Weddings,"subsection_Wine, Beer & Cocktails"
userID,,,,,,,,,,,,,,,,,,,,,
2593,0,0,0,0,2,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
8010,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8638,0,0,0,0,0,0,1,1,0,0,...,0,0,0,0,0,0,0,0,0,0
13323,0,0,0,0,0,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
17282,0,2,0,0,3,0,1,0,2,0,...,2,0,0,0,3,2,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109551783,0,0,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109587542,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109738098,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109837657,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
109978040,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

### Calculate Recommendations

In [104]:
from sklearn.metrics.pairwise import cosine_similarity # TODO: implement from scratch?
similarity_array = cosine_similarity(user_features_matrix, item_features_matrix)
similarity_df = pd.DataFrame(
    similarity_array,
    index=user_features_matrix.index,
    columns=item_features_matrix.index
)
similarity_df.to_csv("similarity_df.csv")
similarity_df

,nyt://article/69a7090b-9f36-569e-b5ab-b0ba5bb3ccbd,nyt://article/9edddb54-0aa3-5835-a833-d311a76f1e7c,nyt://article/04bc90f0-b20b-511c-b5bb-3ce13194163f,nyt://article/bd8647b3-8ec6-50aa-95cf-2b81ed12d2dd,nyt://article/ac742403-9ccd-522f-9a1e-a90feb6c0acd,nyt://article/dea10063-7440-586f-bc32-db1dbaa9893f,nyt://article/dfd5bb59-f330-5c01-ae02-221e6f9cae7a,nyt://article/6227c991-6a3d-5eb1-92c9-a618f6e20dbd,nyt://article/7d9a4f78-44ef-5756-bc2b-4c13cbfa0d5a,nyt://article/da74e3b3-f027-5b03-9052-0bc2e69a2f3e,...,nyt://article/23ec0066-2831-599d-bbff-cef34498ab07,nyt://article/2ae8b3b1-f038-5953-a83a-8b75389010da,nyt://article/67b90b5b-fbb1-5f4b-ab12-7fcc24793bcf,nyt://article/d118dda5-b976-56f9-81c7-a961dcff8e84,nyt://article/46182ac4-985b-5b2d-9c4c-5ca4c9552fdd,nyt://article/b9c293a0-dfb4-5630-9948-8a39be8afce8,nyt://article/203dd447-5d08-5745-95b8-b97de174d4b9,nyt://article/1e2029bd-8b3d-5e1e-9e78-28e5ff746998,nyt://article/697c75a8-2600-5e81-98ac-38193d89ae12,nyt://article/49cedd40-d966-5fa1-a04a-1db9abc2756a
userID,,,,,,,,,,,,,,,,,,,,,
2593,0.185341,0.0,0.030890,0.030890,0.680985,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.226995,0.370681,0.370681,0.000000,0.000000,0.302660,0.403547
8010,0.046424,0.0,0.000000,0.000000,0.000000,0.278543,0.278543,0.278543,0.000000,0.000000,...,0.00000,0.0,0.000000,0.644383,0.092848,0.092848,0.000000,0.000000,0.075810,0.947623
8638,0.396059,0.0,0.099015,0.099015,0.080845,0.000000,0.000000,0.000000,0.099015,0.161690,...,0.19803,0.0,0.099015,0.242536,0.693103,0.693103,0.000000,0.000000,0.565916,0.161690
13323,0.553519,0.0,0.000000,0.000000,0.150649,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.075324,0.968658,0.968658,0.000000,0.000000,0.790906,0.150649
17282,0.552536,0.0,0.000000,0.000000,0.000000,0.157867,0.157867,0.157867,0.039467,0.000000,...,0.00000,0.0,0.118401,0.193347,0.868271,0.868271,0.128898,0.193347,0.805614,0.128898
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109551783,0.000000,0.0,0.250000,0.250000,0.408248,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
109587542,0.267261,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.145479,...,0.00000,0.0,0.000000,0.727393,0.534522,0.534522,0.000000,0.000000,0.436436,0.727393
109738098,0.500000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.816497,0.000000
109837657,0.426401,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.348155,0.852803,0.852803,0.000000,0.000000,0.696311,0.522233
109978040,0.000000,0.0,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.00000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000

In [105]:
articles_lookup = articles.set_index("uniqueID", drop=False)

def print_article(i, article_id, score=None):
    if article_id in articles_lookup.index:
        row = articles_lookup.loc[article_id]
        title = row.get("headline", row.get("title", "N/A"))
        abstract = row.get("abstract", "N/A")
        newsdesk = row.get("newsdesk", "N/A")
        section = row.get("section", "N/A")
        subsection = row.get("subsection", "N/A")
    else:
        title = abstract = newsdesk = section = subsection = "N/A"

    score_str = f" | score: {score:.5f}" if score is not None else ""
    print(f"{i}. article_id: {article_id}{score_str} | {title} | {abstract} | {newsdesk=} | {section=} | {subsection=}")

def print_results(user_id, recommendations=5):

    commented_ids = []
    if user_id in utility_matrix.index:
        commented = utility_matrix.loc[user_id]
        commented_ids = commented[commented > 0].index.tolist()

    scores = similarity_df.loc[user_id].sort_values(ascending=False)
    # remove alreayd commented articles
    scores = scores.drop(index=commented_ids, errors="ignore")


    print(f"=== Top {len(scores.head(recommendations))} recommendations for user {user_id}:")
    for i, (article_id, score) in enumerate(scores.head(recommendations).items(), start=1):
        print_article(i, article_id, score)

    print(f"\n=== Articles already commented by user {user_id} ({len(commented_ids)}):")
    for i, article_id in enumerate(commented_ids, start=1):
        print_article(i, article_id)

print_results(similarity_df.index[0], 10)

=== Top 10 recommendations for user 2593:
1. article_id: nyt://article/559b427e-a5af-5a06-b668-bd83670e1ca3 | score: 0.75665 | China Pledged to Build a New Hospital in 10 Days. It’s Close. | State news outlets reported that the 1,000-bed facility would accept patients from Monday even as construction workers raced to complete it. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
2. article_id: nyt://article/643a5a43-56e8-5f61-8f30-e79268d7b2e2 | score: 0.75665 | In Blow to Beijing, Taiwan Re-elects Tsai Ing-wen as President | The victory was a remarkable comeback for Ms. Tsai and suggested that Beijing’s pressure campaign had backfired. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
3. article_id: nyt://article/89f51792-75fe-560f-a798-031c32fdd212 | score: 0.75665 | As Coronavirus Spreads, So Does Anti-Chinese Sentiment | Fears of the outbreak have fueled xenophobia as a wave of panic spreads, sometimes outstripping practical concerns. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
4. article_id: nyt://article/3ed39196-b92b-50d7-abcf-9721a88029d7 | score: 0.75665 | As Virus Spreads, U.S. Temporarily Bars Foreigners Who’ve Visited China | Most foreign nationals will not be allowed to enter the United States if they’ve been to China in the preceding two weeks. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
5. article_id: nyt://article/38a59b7b-32a9-5cf4-b232-253331f05b73 | score: 0.75665 | Hong Kong Tightens Border as Medical Workers Call for Shutdown | More than 2,500 hospital employees went on strike, demanding a complete closing of traffic from mainland China to lessen the risk of spreading coronavirus. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
6. article_id: nyt://article/7e2c2a9b-28da-5167-8886-830d023d2b54 | score: 0.75665 | Mumbai Police Play a Trick on Honking Drivers | It involves a red light hooked to a decibel meter, and the timer resets when harsh horns get too loud. Now, other cities are inquiring. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
7. article_id: nyt://article/40edd806-d950-5b6f-a751-d7ddbc3e9f92 | score: 0.75665 | Beijing in the Time of Coronavirus: No Traffic, Empty Parks and Fear | The Chinese capital, like other cities far from the epidemic’s center, has imposed restrictions and shut down public spaces, straining the ties that bind society. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
8. article_id: nyt://article/1cb5b035-443d-57d7-819c-8b6e5d5c64f0 | score: 0.75665 | China’s Omnivorous Markets Are in the Eye of a Lethal Outbreak Once Again | The coronavirus that has spread from Wuhan has been linked to the sale of live wildlife at a market that experts describe as a perfect incubator for novel pathogens. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
9. article_id: nyt://article/f1607a68-3095-5155-8b4c-a4b7bfccc808 | score: 0.75665 | Wuhan, Center of Coronavirus Outbreak, Is Being Cut Off by Chinese Authorities | The sudden restrictions — announced after the official death toll nearly doubled — could upend the travel plans of millions of Chinese citizens, who travel in huge numbers during the Lunar New Year holiday. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
10. article_id: nyt://article/6a8cea91-454f-54d8-ba0f-f1c2cc469306 | score: 0.75665 | China Looms Over Taiwan’s Election, Giving a Boost to the Incumbent | China’s hostility and the protests in Hong Kong have reversed the political fortunes of President Tsai Ing-wen, raising alarms in Beijing. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'

=== Articles already commented by user 2593 (30):
1. article_id: nyt://article/016cf3b3-56e9-53e4-882c-549209211afb | A Sea of Mourners in Iran, and New Threats From Both Sides | Vast crowds thronged the streets of Tehran as a funeral was held for Maj. Gen. Qassim Suleimani, who was killed in an American drone strike on Friday. | newsdesk='Foreign' | section='World' | subsection='Middle East'
2. article_id: nyt://article/0b4a295e-becc-5779-92c3-3653f6bb4b0d | Iran ‘Concludes’ Attacks, Foreign Minister Says | Iran does not seek “seek escalation or war,” the minister, Mohammad Javad Zarif, said in a tweet hours after Iran launched missile strikes against Americans in Iraq. | newsdesk='Foreign' | section='World' | subsection='Middle East'
3. article_id: nyt://article/11e85e43-5924-5997-9d69-887bd91b63bc | Amid Tight Security, Virginia Gun Rally Draws Thousands of Supporters | Some 22,000 people, many of them armed, flooded the streets around the State Capitol to protest gun control proposals from the new Democratic majority. | newsdesk='National' | section='U.S.' | subsection=nan
4. article_id: nyt://article/13520d15-58cd-5fc3-9c50-7725f2da116b | Trump Legal Team Adds Starr and Dershowitz for Senate Trial | Ken Starr and a third lawyer named to the team, Robert Ray, were independent counsels who investigated President Bill Clinton. | newsdesk='Washington' | section='U.S.' | subsection='Politics'
5. article_id: nyt://article/22be24e7-b140-5997-a025-2f34e4ddc6fa | Suleimani Died as He Had Killed | Now the United States must establish a balance of hope and fear in the Middle East. | newsdesk='OpEd' | section='Opinion' | subsection=nan
6. article_id: nyt://article/278b7445-710c-59c8-a8eb-3d9e7160326d | Hong Kong Reports First Death From Coronavirus Outbreak | The death was the second from the virus outside mainland China. The patient was a 39-year-old man who had visited Wuhan and returned to Hong Kong on Jan. 23. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
7. article_id: nyt://article/2dcda045-a0f9-572e-8a1e-29c0443b5261 | Alarm Grows as Markets Tumble and Death Toll Rises | Health officials in the United States said more than 100 people were being evaluated for possible infection. Of the nearly 3,000 people who have contracted the virus, the vast majority live in China. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
8. article_id: nyt://article/2e432a3b-0937-5f45-baf4-34d3d12a5536 | Toll From Outbreak Climbs in China as Infections Reach Europe and Australia | Shanghai Disneyland shut down, hospitals pleaded for help, France reported three cases and the youngest victim so far was identified. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
9. article_id: nyt://article/44a4d922-0f9c-5b48-b7e4-23879b6dbac6 | Trump Focuses on Economy at Davos, Seeking a Counter to Impeachment | President Trump made his first appearance on the international stage since the House sent impeachment articles to the Senate, on the day his trial is set to begin in earnest. | newsdesk='Washington' | section='Business Day' | subsection=nan
10. article_id: nyt://article/4de8f206-87d3-578f-90a6-8511ad8ef4e6 | Coronavirus: Death Toll Climbs, and So Does the Number of Infections | The number of known cases of the new virus rose by nearly a third overnight. A shortage of test kits has led experts to warn that the real number may be higher. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
11. article_id: nyt://article/4fd64086-c96a-5516-82cd-7f1255f07997 | 8 Americans Were Hurt in Iranian Strike, Military Says, Despite Trump Statements | The service members showed symptoms of concussions after Iranian missiles hit air bases in Iraq last week. President Trump had said that “no Americans were harmed.” | newsdesk='Foreign' | section='World' | subsection='Middle East'
12. article_id: nyt://article/544420fe-ca42-5499-ac59-a1a4c16f6eef | At the Stroke of Brexit, Britain Steps, Guardedly, Into a New Dawn | On a rainy evening of dampened festivities, its epoch-making departure stirred hopes and fears, but also relief that the ordeal is finally over. | newsdesk='Foreign' | section='World' | subsection='Europe'
13. article_id: nyt://article/5beb2af1-57f2-56f5-b7a9-2c7e5c64c4e8 | Coronavirus Death Toll Climbs in China, and a Lockdown Widens | At least 25 people have died and more than 800 have been sickened by the mysterious illness, health officials said. The travel restrictions imposed on Wuhan were extended to at least four more cities. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
14. article_id: nyt://article/5d85834d-aa85-501e-811b-81aff57c6cb0 | The Trump Administration’s Fluctuating Explanations for the Suleimani Strike | Over 10 days, officials have struggled to rationalize the decision that risked a war with Iran. | newsdesk='Washington' | section='U.S.' | subsection='Politics'
15. article_id: nyt://article/62b0c505-8e0d-550e-a04f-46d95bc9f531 | Iranian Missile Accidentally Brought Down Ukrainian Jet, Officials Say, Citing Early Evidence | Western intelligence showed that Iran was responsible for the plane crash, suggesting that the deaths of those aboard were a consequence of the heightened tensions between Washington and Iran. | newsdesk='Washington' | section='World' | subsection='Middle East'
16. article_id: nyt://article/6440c6aa-0f58-5797-a130-4eaba7bf1da4 | More Than 7,700 Cases of Coronavirus Recorded Worldwide | Chinese officials have confirmed over 7,700 cases of the mysterious illness as foreign governments airlifted their citizens out of Wuhan, the outbreak’s epicenter. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
17. article_id: nyt://article/65cff85d-1be4-5453-87f8-07049b4d2514 | Trump Targets Michelle Obama’s School Nutrition Guidelines on Her Birthday | The Agriculture Department proposed a rule that would further unravel nutrition standards set by Mrs. Obama when she was first lady. | newsdesk='Washington' | section='U.S.' | subsection='Politics'
18. article_id: nyt://article/79d8d45d-c37f-555e-b299-9805923c25d3 | Iranian Blood Is on Our Hands, Too | General Suleimani is not the only one who harmed civilians. | newsdesk='OpEd' | section='Opinion' | subsection=nan
19. article_id: nyt://article/84217089-8f78-5782-99ef-f52651548a39 | SARS Stung the Global Economy. The Coronavirus Is a Greater Menace. | In the nearly 20 years since SARS, China’s importance in the global economy has grown exponentially. | newsdesk='Business' | section='Business Day' | subsection='Economy'
20. article_id: nyt://article/8767d4ed-85f7-56a0-a1ac-cdfa4f702b82 | Yesterday’s Bread, Today’s Lush Fatteh | Leftover pita is never a waste: Yotam Ottolenghi puts it to work layered amid chickpeas, tahini, herbs and chile oil. | newsdesk='Dining' | section='Food' | subsection=nan
21. article_id: nyt://article/8c5da820-fea9-572f-9bc1-278d053f50d2 | How Does President Sanders Sound to You? | Bernie is surging and may have found his moment. | newsdesk='OpEd' | section='Opinion' | subsection=nan
22. article_id: nyt://article/8d9656f8-722a-5b70-9713-a129027f2ca7 | Every Time Palestinians Say ‘No,’ They Lose | Things rarely go well for those who try to live history backward. | newsdesk='OpEd' | section='Opinion' | subsection=nan
23. article_id: nyt://article/afc48a2a-69c0-5412-b1aa-adaeca49bb81 | Deaths in China Rise, With No Sign of Slowdown | Hyundai is suspending production in South Korea amid supply chain problems linked to the coronavirus, and Japan quarantined a cruise ship where 10 infections were found. | newsdesk='Foreign' | section='World' | subsection='Asia Pacific'
24. article_id: nyt://article/b6a8cc7e-eb8f-55d4-8c91-073690a3b342 | How China Obtains American Trade Secrets | Companies have long accused Chinese rivals of swiping or seizing valuable technology. Beijing promises to ban those practices, but enforcement could be tough. | newsdesk='Business' | section='Business Day' | subsection=nan
25. article_id: nyt://article/d5315a04-3a81-5f8a-8fb3-f378b25715e9 | Trump Signs China Trade Deal, Putting Economic Conflict on Pause | An initial pact, cooling tensions in an election year, follows months of escalating tariffs and a trade war that seemed as if it would never end. | newsdesk='Washington' | section='Business Day' | subsection='Economy'
26. article_id: nyt://article/d77e45a7-71d6-5f27-b240-29e17b2ff84a | ‘There Was a Woman Sitting Alone at the End of the Bar’ | Out to dinner on a crisp fall night, a sandwich to go and more reader tales of New York City in this week’s Metropolitan Diary. | newsdesk='Metropolitan' | section='New York' | subsection=nan
27. article_id: nyt://article/e038497e-e593-522e-b3b0-0007c90cf8cb | The American-Iranian Psychosis, Next Chapter | The mullahs are cold calculators. | newsdesk='OpEd' | section='Opinion' | subsection=nan
28. article_id: nyt://article/eaa90a71-d4a0-5629-b053-8bde52d083cb | Wuhan Coronavirus Looks Increasingly Like a Pandemic, Experts Say | Rapidly rising caseloads alarm researchers, who fear the virus may make its way across the globe. But scientists cannot yet predict how many deaths may result. | newsdesk='Science' | section='Health' | subsection=nan
29. article_id: nyt://article/f966f1ee-b6c8-549a-ac18-22c1963dbe7b | Barr Asks Apple to Unlock Pensacola Killer’s Phones, Setting Up Clash | The request set up a collision between law enforcement and big technology firms in the latest battle over privacy and security. | newsdesk='Washington' | section='U.S.' | subsection='Politics'
30. article_id: nyt://article/f9f5d936-5ae3-5de5-933a-207ff9555c3a | Anyone but Trump? Not So Fast | Let’s not exchange one reckless president for another. | newsdesk='OpEd' | section='Opinion' | subsection=nan